on:
    release:
      types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Github Releases To Discord
      uses: sillyangel/releases-to-discord@v1.0.0
      with:
        webhook_url: https://discord.com/api/webhooks/1012539231815602217/mjQdYOuy3-jrbtKYoV3RONVtSVmORAbdxlWRcKfflCjcjSEGaB-y_4lv57pVOAWfbZSe
        color: "2105893"
        username: "Release Changelog"
        avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"